### ISSUE TITLE
Ошибка установки

### ISSUE THREAD

**Issue by Kirill** [KovAlexey/EDTContentAssistAutoOpen#1]
EDT 2023.2.4. При установке ошибка:
```
Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Устанавливаемое программное обеспечение: Auto open content assistant 0.0.1.v202406232325 (org.kovalexey.edt.autoopencontentassistant.feature.group 0.0.1.v202406232325)
  Отсутствующее требование: Auto open propossal 0.0.1.v202406232325 (org.kovalexey.edt.autoopenpropossal 0.0.1.v202406232325) требует 'osgi.bundle; com._1c.g5.v8.dt.bsl.ui 20.0.0', но его не удалось найти
  Невозможно удовлетворить зависимость:
    Из: Auto open content assistant 0.0.1.v202406232325 (org.kovalexey.edt.autoopencontentassistant.feature.group 0.0.1.v202406232325)
    Что: org.eclipse.equinox.p2.iu; org.kovalexey.edt.autoopenpropossal [0.0.1.v202406232325,0.0.1.v202406232325]
```
![image](https://github.com/KovAlexey/EDTContentAssistAutoOpen/assets/302940/87822f2a-c091-4568-91e1-c07925278f94)

**Comment by KovAlexey** [comment]
Плагин разрабатывался и собирался под актуальную на текущий момент версию 2023.3.5. Понижать версию таргет платформы не планирую.
Но, впрочем, если ее поменять и пересобрать - должно собраться без проблем

**Comment by KovAlexey** [comment]
Я посмотрю.
Вроде можно настроить, чтоб под несколько таргет платформ собиралось

**Comment by KovAlexey** [comment]
Плагин обновлен. Теперь устанавливается на версию 2024.1.3

**Comment by KovAlexey** [comment]
Обратил внимание снова на версию.
Все же выпуск для более старых версий более не планируется
